### ISSUE TITLE
Innovation.txt file issues .... missing/corrupt file causes app to crash

### ISSUE THREAD

**Issue by frankk74** [jsparkes/innovation#6]
If the file Innovation.txt is corrupted or missing the app threw out of bounds error (see below for messages)

Added check (in initialize_card_data() ) for missing data file. But this doesn't address corrupted data (which should never happen).

Is there a better way to embed data into code? could it just be a bunch of DIM statements?

----------------------snip snip-------------------------------------------------------------

Errors:

Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

Index was outside the bounds of the array.

------------------

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Innovation.Main_Renamed.launch_game(Object& players)

**Comment by jsparkes** [comment]
I could write a script to transform the data into code, shouldn't be too difficult.  It should solve the EOL problem as well.  (I changed my local git config to not change the EOL chars, but it's a bit too late.  As least I won't change them back in the fixed files.)

**Comment by frankk74** [comment]
Well VS build and packaging adds the file... maybe the best way is just to checksum it for verification? and I guess dotnet has that functionality built it?

 Get-FileHash .\Innovation.txt

Algorithm       Hash                                                                  
---------       ----           
SHA256          D7693A3245ED901B581C431CE367BE47DA12F543EE525FA9613D429F13955218

https://riptutorial.com/dot-net/example/29285/sharpgenerate-sha1-checksum-of-a-file

**Comment by frankk74** [comment]
Can you try to assign this issue to me?

I don’t seems to have enough access to do that?

**Comment by frankk74** [comment]
When "Publishing" app via VS 2022 all files are bundled correctly. Likelihood of files getting corrupted is small. Closing as will not fix.
